- src/component/detail/Detail.js
- src/component/news/NewsTest.js
- src/component/stock/MoveStockInfo.js
- src/component/stock/MoveStockInfo.scss
- src/component/stock/StockTemplate.js
> feat: 슬라이드구현, 디테일화면 거의 끝나감

- src/component/detail/Detail.js
- src/component/layout/Header.js
- src/component/news/NewsTest.js
> feat: 검색부분 오류 수정 중

- src/component/info/InfoTest.js
- src/component/layout/Header.js
- src/component/stock/MoveStockInfo.js
- src/component/stock/StockTemplate.js
[feat: 디테일 화면 종목정보 오류 수정 및 구현]
> feat: 디테일 화면 종목정보 오류 수정 및 구현

- src/component/layout/Header.js
- src/component/stock/MoveStockInfo.js
- src/component/stock/StockTemplate.js
> fix: 헤더와 슬라이드 오류 수정

- src/component/detail/Candle.js
- src/component/detail/Detail.js
> feat: 디테일화면 그래프 실시간 반영

- src/component/detail/Detail.js
- src/component/detail/Detail.scss
- src/component/layout/Header.js
- src/component/user/Login.js
- src/component/util/AuthContext.js
> feat: 디테일화면과 헤더 수정

- src/component/detail/Detail.js
- src/component/layout/Header.js
- src/component/stock/StockTemplate.js
- src/component/user/MyPage.scss
> fix: 헤더의 검색창 모달오류 등 수정완료

- src/component/detail/Detail.js
- src/component/info/InfoTest.js
- src/component/news/NewsTest.js
- src/component/stock/MoveStockInfo.js
- src/component/stock/StockTemplate.js
> feat: 디테일화면에서 관심종목 기능 구현

- public/index.html
- src/component/detail/Detail.js
- src/component/stock/StockTemplate.js
- src/component/stock/StockTemplate.scss
- src/component/user/Login.js
- src/component/util/AuthContext.js
> feat: 홈화면 관심종목 기능 구현 및 디자인

- package-lock.json
- package.json
- src/component/detail/AskingPrice.js
- src/component/detail/Detail.js
- src/component/stock/StockTemplate.js
- src/component/user/IdModal.scss
- src/component/user/Login.js
- src/component/user/PasswordModal.scss
[feat: 매수매도 기능(유저정보와 연동 성공) 구현]
> feat: 매수매도 기능(유저정보와 연동 성공) 구현

- README.md
- src/component/detail/Detail.js
- src/component/news/NewsTest.js
- src/component/stock/StockTemplate.js
- src/component/stock/StockTemplate.scss
> fix: 매수매도 기능 오류 수정

- src/component/detail/Detail.js
- src/component/stock/OverallRank.js
> fix: 매수매도 기능 오류 수정 끝

- src/component/stock/OverallRank.js
- src/component/stock/OverallRank.scss
> feat: 랭킹 상세보기 기능 구현

- src/component/detail/Detail.js
- src/component/detail/RcmMbti.js
> feat: 디테일화면 내 종목 기능 구현

- src/component/detail/Detail.js
- src/component/detail/Detail.scss
- src/component/stock/MoveStockInfo.js
- src/component/user/MyPage.js
- src/component/user/MyPageViewInfo.js
> feat: 디테일 내주식과 마이페이지 내정보수정

- src/component/board/BoardDetail.js
- src/component/board/RegistFrame.js
- src/component/detail/Detail.js
- src/component/detail/InvestmentStrategy.js
- src/component/detail/MbtiTip.js
- src/component/detail/MbtiTip.scss
- src/component/layout/Header.js
[feat: 게시판 기능추가 및 디테일 mbti 설명 추가]
> feat: 게시판 기능추가 및 디테일 mbti 설명 추가

- src/component/user/MyPage.js
> fix: 마이페이지 수정

- src/component/adminPage/stats/UserGroupByCareer.js
> feat: mbti별 유저 수 기능 구현

- src/component/adminPage/stats/UserByMBTI.js
- src/component/adminPage/stats/UserGroupByCareer.js
[feat: MBTI별 평균 손익,경력 별 평균 손익 화면단 구현]
> feat: MBTI별 평균 손익,경력 별 평균 손익 화면단 구현

- src/component/adminPage/AdminSearchBar.js
- src/component/adminPage/UserInfoTable.js
> feat: 관리자 유저정보 보기, 검색 구현

- src/component/adminPage/AdminSearchBar.js
- src/component/adminPage/Dropdown.js
- src/component/adminPage/UserInfoTable.js
- src/component/user/Login.js
[feat:관리자페이지 검색기능 및 초기화 기능 구현]
> feat:관리자페이지 검색기능 및 초기화 기능 구현

- src/App.css
- src/App.js
- src/component/layout/MarketInfo.js
- src/component/user/Delete.js
- src/component/user/MyPage.js
- src/component/util/NotFound.js
> feat: 회원탈퇴 수정 및 404페이지 구현

- src/component/stock/OverallRank.js
> fix: 메인페이지 오류 수정

- src/component/detail/InvestmentStrategy.js
- src/component/user/Join.js
> fix: MBTI 안내 text 수정

- src/component/user/MyPages/MyAsset.js
- src/component/util/NotFound.js
fix: 404페이지 수정fix: 마이페이지 자산관리 수정
> fix: 404페이지 수정fix: 마이페이지 자산관리 수정

- src/component/adminPage/RollControl.js
> fix: RollControl modal 삭제
